### ISSUE TITLE
Seems to be an issue with `pod install` during the setup tasks listed in the ReadMe

### ISSUE THREAD

**Issue by AustinInSeattle** [the-blue-alliance/the-blue-alliance-ios#83]
While following the ReadMe, the `pod install` command results in this error:
```
Austins-MacBook-Pro:js austin$ pod install
[in /Users/austin/the-blue-alliance-ios]
Setting up CocoaPods master repo
  $ /usr/bin/git clone https://github.com/CocoaPods/Specs.git master --progress
  Cloning into 'master'...
  remote: Counting objects: 1416611, done.        
  remote: Compressing objects: 100% (7191/7191), done.        
  remote: Total 1416611 (delta 5468), reused 6128 (delta 2336), pack-reused 1406611        
  Receiving objects: 100% (1416611/1416611), 413.01 MiB | 13.57 MiB/s, done.
  Resolving deltas: 100% (722899/722899), done.
  Checking out files: 100% (170046/170046), done.

CocoaPods 1.3.0.beta.3 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.3.0.beta.3

Setup completed
Analyzing dependencies
Fetching podspec for `React` from `js/node_modules/react-native`
Fetching podspec for `Yoga` from `js/node_modules/react-native/ReactCommon/yoga`
Downloading dependencies
Installing AppAuth (0.9.1)
Installing GTMAppAuth (0.6.1)
Installing GTMSessionFetcher (1.1.11)
Installing PureLayout (3.0.2)
Installing React (0.43.0)
Installing TBAKit (2.0.0)
Installing Yoga (0.43.0.React)
Installing youtube-ios-player-helper (0.1.6)
Generating Pods project
[!] An error occurred while processing the post-install hook of the Podfile.

unknown file type: Pods/Target Support Files/Pods-the-blue-alliance-ios/Pods-the-blue-alliance-ios-acknowledgements.plist

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1375:in `copy'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:463:in `block in copy_entry'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1485:in `call'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1485:in `wrap_traverse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:460:in `copy_entry'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:435:in `block in cp_r'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1558:in `block in fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1574:in `fu_each_src_dest0'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1556:in `fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:434:in `cp_r'
/Users/austin/the-blue-alliance-ios/Podfile:25:in `block (2 levels) in from_ruby'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.2.1/lib/cocoapods-core/podfile.rb:179:in `call'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.2.1/lib/cocoapods-core/podfile.rb:179:in `post_install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:670:in `run_podfile_post_install_hook'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:658:in `block in run_podfile_post_install_hooks'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/user_interface.rb:142:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:657:in `run_podfile_post_install_hooks'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:181:in `block in generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:178:in `generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:115:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/command/install.rb:41:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

I'm not sure if this is something I did or just a standard during the install on a fresh build. Does anybody have any suggestions? Also, I'm mostly looking to utilize this as a method for pulling TBA data into my own iOS app later on.

**Comment by ZachOrr** [comment]
Hey, Austin! It looks like Cocoapods is just failing to generate the acknowledgments file we use to say what open source libraries we use. Make sure you're running `pod install` in the root directory (`the-blue-alliance-ios`) and not the `js` folder. I've updated the `README` with a command to return the user to the proper directory after setting up the npm whatnot

If you're looking to pull TBA data into your own iOS app, check out the [TBAKit](https://github.com/ZachOrr/TBAKit), the API wrapper we use to power TBA for iOS

**Comment by ZachOrr** [comment]
@AustinInSeattle Any luck on this?
